spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///springboot
    dbcp2:
      min-idle: '10'
      max-total: '100'
      max-wait-millis: '60000'
    type: org.apache.commons.dbcp2.BasicDataSource
    